# Generated by Django 5.2.17 on 2026-09-23 00:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('fiksi', 'Fiksi'), ('non-fiksi', 'Non-fiksi'), ('komik', 'Komik'), ('referensi', 'Referensi')], default='fiksi', max_length=20)),
                ('synopsis', models.TextField()),
                ('pages', models.PositiveIntegerField()),
                ('cover_url', models.URLField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('published_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
